lab3: Main.o S-Linked_list.o XML_parsed_elems.o
	gcc -o lab3 Main.o S-Linked_list.o XML_parsed_elems.o
Main.o: Main.c
	gcc -c Main.c
S-Linked_list.o: S-Linked_list.c
	gcc -c s-Linked_list.c
XML_parsed_elems.o: XML_parsed_elems.c
	gcc -c XML_parsed_elems.c